const Data_64_provinces_and_cities = [
  "Đà Nẵng",
  "Hồ Chí Minh",
  "Hà Nội",
  "An Giang",
  "Bà Rịa-Vũng Tàu",
  "Bạc Liêu",
  "Bình Định",
  "Bến Tre",
  "Cà Mau",
  "Cao Bằng",
  "Thừa Thiên - Huế",
  "Tiền Giang",
  "Thanh Hóa",
  "Thái Nguyên",
  "Quảng Ninh",
  "Quảng Ngãi",
  "Quảng Nam",
  "Quảng Bình",
  "Phú Yên",
  "Phú Thọ",
  "Ninh Thuận",
  "Nghệ An",
  "Nam Định",
  "Hải Phòng",
  "Hà Tĩnh",
  "Gia Lai",
  "Đắk Lắk",
  "Cần Thơ",
  "Bắc Ninh",
  "Quảng Trị",
];

export default Data_64_provinces_and_cities;
